### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by beuoon** [BlockchainEducation/BEDU#1]
---
**Cursor**
- 정보 탐색
  - (v)```private final Map<String, Object> db```
  - (v)```private final List<String> keys```
  - (v)```private int idx```
  - (m)```public Pair<String, Object> head()```
  - (m)```public Pair<String, Object> tail()```
  - (m)```public Pair<String, Object> next()```
  - (m)```public Boolean hashNext()```
  - (m)```public Pair<String, Object> get(int idx)```

**Bucket**
- 정보 관리
  - (v)```private final Map<String, Object> db```
  - (m)```public void put(String key, Object)```
  - (m)```public Object get(String key)```
  - (m)```public void delete(String key)```
  - (m)```public void clear()```

- Cursor 생성
  - (m)```public Cursor cursor()```

**Database**
- Bucket 관리
  - (v)```private final Map<String, Bucket> buckets```
  - (m)```public Bucket getBucket(String name)```

---
**Block**
- 블록 정보
  - (m)```byte[] getPrevBlockHash()```
  - (m)```byte[] getHash()```
  - (m)```int getHeight()```

**Blockchain**
- 블록 관리
  - (m)```public boolean addBlock(Block block)```
  - (m)```public Block findBlock(String hash)```
  - (m)```public String getLastBlockHash()```
  - (m)```public int getHeight()```
---
**NetworkListener**
- 메세지 수신
  - (m)```public <T> void listen(String from, T message)```

**Network**
- Listener 관리
  - (sv)```public static final Map<String, NetworkListener> Listeners```
  - (sm)```public static void AddListener(String nodeId, NetworkListener eventListener)```
  - (sm)```public static void RemoveListener(String nodeId)```

- 메세지 전송
  - (sm)```private static <T> void CallEvent(String from, String to, T message)```
  - (sm)```public static <T> void Send(String from, String to, T message)```
  - (sm)```public static <T> void Broadcast(String from, List<String> to, T message)```

---
**Node**
- 고유 ID
  - (v)```protected final String nodeId```
  - (m)```public String getNodeId()```

- (비)활성화
  - (m)```public void open()```
  - (m)```public void close()```

- 노드 연결 관리
  - (v)```protected final List<String> connections```
  - (m)```public void connectTo(String to)```
  - (m)```public void disconnectTo(String to)```
---

**Comment by beuoon** [comment]
어느 플랫폼에서나 공통적으로 사용한다고 생각되는 것들을 정리해봤습니다.
그런데 맞는지 모르겠네여.. 검토 부탁드립니다.

**Comment by beuoon** [comment]
hash값 byte[]로 관리할지 String으로 관리할지 결정해야 됩니다.

**Comment by bperhaps** [comment]
netwrok 패키지에서 message는 플랫폼 패키지에서 정의하게 하는게 맞는 것 같아요.  플랫포 마다 메세지 형태가 다를테니. 그렇게 하고 NetworkListener 인터페이스랑 Network 클래스의 Message는 제네릭 처리하도록 하면 더 깔끔할듯 합니다.

Database 입력을 byte[]로 했는데 이것도 Object로 수정하는 방향으로 갑시다. 시뮬레이터기 때문에 데이터를 직렬화 시킬 필요를 못느끼겠네요.

hash값은 Hex로 변환하여 String으로 관리하는편이 깔끔할 것 같습니다.

위 수정사항 반영 후 커밋 부탁 드려요
